import { Providers } from "@/app/[locale]/providers";
import { Suspense } from "react";
import initTranslations from "@/app/i18n";
import { GlobalProvider } from "@/app/GlobalProvider";
import TranslationsProvider from "@/app/TranslationsProvider";
import Header from "@/components/header/Header.jsx";
import Footer from "@/components/footer/Footer.jsx";
import Loading from "./loading";
import "../globals.css";

const i18nNamespaces = [
  "header",
  "footer",
  "terms",
  "notfound",
  "about",
  "home",
  "vacancies",
  "how-it-works",
  "technical-works",
  "donation",
];

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
  const { _, resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang="uk">
      <body>
        <Providers>
          <TranslationsProvider
            namespaces={i18nNamespaces}
            locale={locale}
            resources={resources}
          >
            <GlobalProvider>
              <Header />
              <main>
                <Suspense fallback={<Loading />}>{children}</Suspense>
              </main>
              <Footer />
            </GlobalProvider>
          </TranslationsProvider>
        </Providers>
      </body>
    </html>
  );
}
